# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "5.8"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1.0'
      - name: Build iOS
        run: xcodebuild -project Demo/Demo.xcodeproj build -sdk iphoneos -scheme 'RichTextKit'
      - name: Test iOS
        run: xcodebuild -project Demo/Demo.xcodeproj test -sdk iphoneos -scheme 'RichTextKitTests' -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' -enableCodeCoverage YES 

          
